---
- hosts: nix
  become: true
  gather_facts: no
  tasks:
    - name: Copy static configurations to target directory
      copy:
        src: "nix/"
        dest: /etc/nixos
        mode: preserve
    - name: Copy secrets
      copy:
        src: "secrets/"
        dest: /var/garuda/secrets
        mode: 600
        directory_mode: 600
#    - name: Build system
#      shell: nixos-rebuild switch
