---
- hosts: nix
  become: true
  gather_facts: no
  tasks:
    - name: Copy static configurations to target directory
      synchronize:
        src: "nix/"
        dest: /etc/nixos/
        rsync_opts:
          - "--exclude=garuda/secrets/"
    - name: Copy buildtime secrets
      copy:
        src: "nix/garuda/secrets/"
        dest: /etc/nixos/garuda/secrets
        mode: "600"
        directory_mode: "600"
    - name: Copy runtime secrets
      copy:
        src: "secrets/"
        dest: /var/garuda/secrets
        mode: "600"
        directory_mode: "600"
#    - name: Build system
#      shell: nixos-rebuild switch
