---
- hosts: nix
  become: true
  gather_facts: no
  tasks:
    - name: Copy static configurations to target directory
      synchronize:
        src: "nix/"
        dest: /etc/nixos/
        rsync_opts:
          - "--exclude=garuda/secrets/"
    - name: Decrypt secrets
      local_action:
        module: copy
        src: "secrets/secrets/"
        dest: "secrets/decrypted/"
        mode: '700'
        directory_mode: '700'
      run_once: true
      become: false
    - name: Copy buildtime secrets
      synchronize:
        src: "secrets/decrypted/buildtime.json"
        dest: /etc/nixos/garuda/secrets/secrets.json
        rsync_opts:
          - "--mkpath"
    - name: Copy runtime secrets
      synchronize:
        src: "secrets/decrypted/"
        dest: "/var/garuda/secrets/"
        delete: yes
        rsync_opts:
          - "--exclude=garuda/buildtime.json"