services:
  # Whoogle search engine
  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - "/var/lib/tor/:size=10M,uid=927,gid=927,mode=1700"
      - "/run/tor/:size=1M,uid=927,gid=927,mode=1700"
    volumes:
      - "./whoogle:/config"
    ports:
      - 127.0.0.1:5000:5000
    environment:
      WHOOGLE_AUTOCOMPLETE: 1
      WHOOGLE_CONFIG_ALTS: 1
      WHOOGLE_CONFIG_LANGUAGE: lang_en
      WHOOGLE_CONFIG_NEW_TAB: 1
      WHOOGLE_CONFIG_SEARCH_LANGUAGE: lang_en
      WHOOGLE_CONFIG_STYLE: ":root{--whoogle-logo:#c4a7e7;--whoogle-page-bg:#faf4ed;--whoogle-element-bg:#f2e9e1;--whoogle-text:#575279;--whoogle-contrast-text:#1f1d2e;--whoogle-secondary-text:#797593;--whoogle-result-bg:#faf4ed;--whoogle-result-title:#d7827e;--whoogle-result-url:#286983;--whoogle-result-visited:#907aa9;--whoogle-dark-logo:#c4a7e7;--whoogle-dark-page-bg:#191724;--whoogle-dark-element-bg:#1f1d2e;--whoogle-dark-text:#e0def4;--whoogle-dark-contrast-text:#e0def4;--whoogle-dark-secondary-text:#908caa;--whoogle-dark-result-bg:#393552;--whoogle-dark-result-title:#9ccfd8;--whoogle-dark-result-url:#3e8fb0;--whoogle-dark-result-visited:#c4a7e7}#whoogle-w{fill:#eb6f92}#whoogle-h{fill:#f6c177}#whoogle-o-1{fill:#ebbcba}#whoogle-o-2{fill:#31748f}#whoogle-g{fill:#9ccfd8}#whoogle-l{fill:#c4a7e7}#whoogle-e{fill:#908caa}"
      WHOOGLE_CONFIG_THEME: dark
      WHOOGLE_CONFIG_URL: https://search.garudalinux.org
      WHOOGLE_CONFIG_VIEW_IMAGE: 1
      WHOOGLE_RESULTS_PER_PAGE: 15
    pids_limit: 50
    restart: always

  # Searxng search engine
  searx:
    image: searxng/searxng:latest
    container_name: searx
    depends_on:
      - filtron
      - morty
    command: -f
    volumes:
      - "./searxng:/etc/searxng:rw"
    ports:
      - 127.0.0.1:8080:8080
    environment:
      BIND_ADDRESS: 0.0.0.0:8080
      BASE_URL: https://searx.garudalinux.org/
      MORTY_URL: https://searx.garudalinux.org/morty/
      MORTY_KEY: ${SX_MORTY_KEY:-?err}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: always

  morty:
    image: dalf/morty:latest
    container_name: morty
    ports:
      - "127.0.0.1:3000:3000"
    command: -timeout 6 -ipv6
    environment:
      MORTY_KEY: ${SX_MORTY_KEY:-?err}
      MORTY_ADDRESS: 0.0.0.0:3000
    logging:
      driver: none
    read_only: true
    cap_drop:
      - ALL
    restart: always

  filtron:
    image: dalf/filtron:latest
    container_name: filtron
    ports:
      - "127.0.0.1:4040:4040"
      - "127.0.0.1:4041:4041"
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searxng:8080
    volumes:
      - "./searxng/rules.json:/etc/filtron/rules.json:rw"
    read_only: true
    cap_drop:
      - ALL
    restart: always

  # Firefox syncserver
  syncserver:
    container_name: syncserver
    image: crazymax/firefox-syncserver:latest
    volumes:
      - "./syncserver:/data"
    ports:
      - 127.0.0.1:5001:5000
    environment:
      FF_SYNCSERVER_ACCESSLOG: True
      FF_SYNCSERVER_FORCE_WSGI_ENVIRON: True
      FF_SYNCSERVER_FORWARDED_ALLOW_IPS: "*"
      FF_SYNCSERVER_PUBLIC_URL: https://ffsync.garudalinux.org
      FF_SYNCSERVER_SECRET: ${FF_SYNCSERVER_SECRET:-?err}
      FF_SYNCSERVER_SQLURI: sqlite:////data/syncserver.db
      TZ: Europe/Berlin
    restart: always

  # Web IRC access
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    volumes:
      - "./thelounge:/var/opt/thelounge"
    ports:
      - 127.0.0.1:9000:9000
    restart: always

  # Password vault
  bitwarden:
    image: vaultwarden/server:testing
    container_name: bitwarden
    volumes:
      - "./bitwarden:/data"
    ports:
      - 127.0.0.1:8082:80
    environment:
      ADMIN_TOKEN: ${BW_ADMIN_TOKEN:-?err}
      DOMAIN: https://bitwarden.garudalinux.org
      SIGNUPS_ALLOWED: True
      SMTP_FROM: noreply@garudalinux.org
      SMTP_HOST: smtp.garudalinux.org
      SMTP_PASSWORD: ${BW_SMTP_PASSWORD:-?err}
      SMTP_PORT: 587
      SMTP_SSL: False
      SMTP_USERNAME: noreply@garudalinux.org
      WEBSOCKET_ENABLED: True
      YUBICO_CLIENT_ID: ${BW_YUBICO_CLIENT_ID:-?err}
      YUBICO_SECRET_KEY: ${BW_YUBICO_ADMIN_SECRET:-?err}
    restart: always

  # Secure pastebin
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    volumes:
      - "./privatebin:/srv/data"
      - "./configs/privatebin.cfg.php:/srv/cfg/conf.php"
    ports:
      - 127.0.0.1:8083:8080
    restart: always

  # Garuda startpage
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - "./startpage:/www/assets"
    ports:
      - 127.0.0.1:8084:8080
    restart: always

  # MongoDB instance
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - "./mongo:/data/db"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-?err}
    restart: always

  # MongoDB admin interface
  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo-express
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 127.0.0.1:8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-?err}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-?err}
  #     ME_CONFIG_MONGODB_URL: ${MONGO_MONGODB_URL:-?err}
  #   mem_limit: 100m
  #   mem_reservation: 20m
  #   cpus: 0.2
  #   restart: unless-stopped
