services:
  # Whoogle search engine
  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /var/lib/tor/:size=10M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    volumes:
      - "./whoogle:/config"
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      WHOOGLE_ALT_IG: insta.dr460nf1r3.org
      WHOOGLE_ALT_RD: reddit.dr460nf1r3.org
      WHOOGLE_ALT_TL: translate.dr460nf1r3.org
      WHOOGLE_ALT_TW: twitter.dr460nf1r3.org
      WHOOGLE_ALT_YT: piped.garudalinux.org
      WHOOGLE_AUTOCOMPLETE: 1
      WHOOGLE_CONFIG_ALTS: 1
      WHOOGLE_CONFIG_LANGUAGE: lang_en
      WHOOGLE_CONFIG_NEW_TAB: 1
      WHOOGLE_CONFIG_SEARCH_LANGUAGE: lang_en
      WHOOGLE_CONFIG_STYLE: ":root{--whoogle-logo:#c4a7e7;--whoogle-page-bg:#faf4ed;--whoogle-element-bg:#f2e9e1;--whoogle-text:#575279;--whoogle-contrast-text:#1f1d2e;--whoogle-secondary-text:#797593;--whoogle-result-bg:#faf4ed;--whoogle-result-title:#d7827e;--whoogle-result-url:#286983;--whoogle-result-visited:#907aa9;--whoogle-dark-logo:#c4a7e7;--whoogle-dark-page-bg:#191724;--whoogle-dark-element-bg:#1f1d2e;--whoogle-dark-text:#e0def4;--whoogle-dark-contrast-text:#e0def4;--whoogle-dark-secondary-text:#908caa;--whoogle-dark-result-bg:#393552;--whoogle-dark-result-title:#9ccfd8;--whoogle-dark-result-url:#3e8fb0;--whoogle-dark-result-visited:#c4a7e7}#whoogle-w{fill:#eb6f92}#whoogle-h{fill:#f6c177}#whoogle-o-1{fill:#ebbcba}#whoogle-o-2{fill:#31748f}#whoogle-g{fill:#9ccfd8}#whoogle-l{fill:#c4a7e7}#whoogle-e{fill:#908caa}"
      WHOOGLE_CONFIG_THEME: dark
      WHOOGLE_CONFIG_URL: https://search.dr460nf1r3.org
      WHOOGLE_CONFIG_VIEW_IMAGE: 1
      WHOOGLE_RESULTS_PER_PAGE: 30
    pids_limit: 100
    restart: always

  # Searxng search engine
  searx:
    image: searxng/searxng:latest
    container_name: searx
    volumes:
      - "./searxng:/etc/searxng"
    ports:
      - 0.0.0.0:8080:8080
    environment:
      BIND_ADDRESS: 0.0.0.0:8080
      BASE_URL: https://searx.garudalinux.org/
      MORTY_URL: https://searx.garudalinux.org/morty/
      SX_MORTY_KEY: ${SX_MORTY_KEY:-?err}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: always